version: '3.9'

services:
  smarteditor_service:
    build:
      context: .
      dockerfile: Dockerfile
    image: smarteditor:latest
    ports:
      - "${SMARTEDITOR_PORT}:${SMARTEDITOR_PORT}"
    volumes:
      - ${SMARTEDITOR_CERTS_DIR}:/certs
      - ./config.json:/app/config.json
      - ./vale.ini:/app/vale.ini
      - ./styles:/app/styles
    environment:
      - LANGCHAIN_PROJECT
      - LANGCHAIN_TRACING_V2
      - LANGCHAIN_ENDPOINT
      - LANGCHAIN_API_KEY
      - SMARTEDITOR_MODEL
      - OPENAI_API_KEY
      - AZURE_OPENAI_ENDPOINT
      - AZURE_OPENAI_API_KEY
      - AZURE_OPENAI_DEPLOYMENT
      - SMARTEDITOR_TOKEN
    command: python main.py --port ${SMARTEDITOR_PORT} --host ${SMARTEDITOR_HOST} --certfile /certs/${SMARTEDITOR_CERTFILE_NAME} --keyfile /certs/${SMARTEDITOR_KEYFILE_NAME}
